const SUPABASE_URL='YOUR_SUPABASE_URL';
const SUPABASE_ANON_KEY='YOUR_SUPABASE_ANON_KEY';
const ADMIN_USERNAME='Rubansu1';
const ADMIN_CODE='Rubansu1';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const app=document.getElementById('app');
app.innerHTML=`
<div id="authScreen" class="screen"><div class="card"><div class="logo">ILLEGAL RUNNER</div><p class="sub">Cours. Plane. Dash. Ameliore-toi.</p><div class="form"><input id="username" class="input" maxlength="18" placeholder="Pseudo"><input id="password" class="input" type="password" minlength="6" placeholder="Mot de passe"><button id="loginBtn" class="btn">Se connecter</button><button id="registerBtn" class="btn secondary">Creer un compte</button><div id="authMsg" class="msg"></div><div class="tiny">Compte sauvegarde sur Supabase.</div></div></div></div>
<div id="mainApp" class="hidden"><header class="topbar"><div class="topline"><div class="brand">Illegal Runner</div><div class="stats"><span class="pill">Pieces <b id="coins">0</b></span><span class="pill">Record <b id="best">0</b> m</span><button id="logoutBtn" class="btn danger">Deconnexion</button></div></div><nav id="nav" class="nav"><button data-page="play" class="active">Jouer</button><button data-page="upgrades">Upgrades</button><button data-page="packs">Packs</button><button data-page="quests">Quetes</button><button data-page="profile">Profil</button><button data-page="admin" id="adminNav" class="hidden">Admin</button></nav></header><main class="main">
<section id="page-play" class="page"><div class="grid"><div class="panel"><div class="toolbar"><button class="modebtn selected" id="infiniteBtn">Infini</button><button class="modebtn" id="levelsBtn">300 niveaux</button></div><div id="levelPicker" class="hidden"><div class="small">300 niveaux avec difficulte progressive.</div><div class="level-grid" id="levelGrid"></div></div><div class="game-wrap"><canvas id="game" width="960" height="540"></canvas><div class="hud"><div class="hud-left"><span class="pill">Distance <b id="distance">0</b> m</span><span class="pill">Pieces <b id="runCoins">0</b></span><span class="pill">Vies <b id="lives">1</b></span></div><div class="hud-right"><span class="pill">Dash <b id="dashText">PRET</b></span></div></div></div><div class="controls"><button id="jumpBtn" class="control jump">SAUT / PLANER</button><button id="dashBtn" class="control dash">DASH <span id="dashCd">PRET</span></button></div><div class="hint small">PC: espace/clic saut, maintenir plane, shift dash. Mobile: maintien du bouton saut.</div></div><div class="panel"><div class="section-title"><h2>Resume</h2><span class="pill" id="modeLabel">Infini</span></div><p>Distance: <b id="sideDistance">0</b> m</p><p>Pieces de la run: <b id="sideCoins">0</b></p><p>Record: <b id="sideBest">0</b> m</p><p>Niveau: <b id="sideLevel">infini</b></p><div class="quest"><b>Bonus temporaires</b><p class="small">5 secondes au debut, puis +1 seconde par upgrade jusqu'a 10 secondes.</p><p>Saut enorme, bouclier, double pieces.</p></div><div class="quest"><b>Dash</b><p class="small">Recharge de 20 secondes. Niveau 6: bouclier qui transperce les obstacles.</p></div></div></div></section>
<section id="page-upgrades" class="page hidden"><div class="panel"><div class="section-title"><h2>Upgrades</h2><span class="pill">Pieces <b class="coinsText">0</b></span></div><div class="upgrade-grid" id="upgradeGrid"></div></div></section>
<section id="page-packs" class="page hidden"><div class="panel"><div class="section-title"><h2>Packs</h2><span class="pill">Pieces <b class="coinsText">0</b></span></div><p class="small">Packs de fonds, personnages et obstacles.</p><div class="cards" id="packGrid"></div><h2>Collection</h2><div class="cards" id="collectionGrid"></div></div></section>
<section id="page-quests" class="page hidden"><div class="grid"><div class="panel"><h2>Quetes quotidiennes</h2><div id="questList" class="cards"></div></div><div class="panel"><h2>Bonus de connexion</h2><div style="font-size:54px;text-align:center">BONUS</div><p style="text-align:center">Serie: <b id="streak">0</b> jour(s)</p><button id="loginReward" class="btn" style="width:100%">Recuperer le bonus</button></div></div></section>
<section id="page-profile" class="page hidden"><div class="panel"><h2>Profil</h2><div id="profileBox"></div></div></section>
<section id="page-admin" class="page hidden"><div class="panel"><h2>Admin</h2><p class="small">Recherche un pseudo puis ajoute des pieces. Compte: Rubansu1.</p><div class="row"><input id="adminSearch" class="input" style="flex:1" placeholder="Rechercher un pseudo"><button class="btn" id="adminSearchBtn">Rechercher</button></div><div id="adminResults"></div></div></section>
</main></div>
<div id="deathModal" class="modal hidden"><div class="modal-box run-result"><h2 id="deathTitle">Run terminee</h2><div class="big-score" id="finalDistance">0 m</div><p>Pieces recuperees: <b id="finalCoins">0</b></p><p>Record: <b id="finalBest">0</b> m</p><button id="replayBtn" class="btn" style="width:100%">Rejouer</button><button id="closeDeath" class="btn secondary" style="width:100%;margin-top:8px">Retour</button></div></div><div id="countdown" class="modal hidden"><div style="font-size:110px;font-weight:1000" id="countNum">3</div></div><div id="toast" class="toast hidden"></div>`;
const $=id=>document.getElementById(id);const st={user:null,p:null,inv:[],mode:'infinite',level:1};let game=null,running=false,runCoins=0,last=0,dashReady=0,jumpHeld=false;
const packs=[['background','forest','Pack Foret',300,'FORET'],['background','desert','Pack Desert',450,'DESERT'],['background','space','Pack Espace',700,'ESPACE'],['background','dark','Pack Sombre',900,'SOMBRE'],['character','ninja','Pack Ninja',500,'NINJA'],['character','robot','Pack Robot',650,'ROBOT'],['character','alien','Pack Alien',800,'ALIEN'],['character','fire','Pack Flamme',1100,'FLAMME'],['obstacle','ice','Pack Glace',500,'GLACE'],['obstacle','lava','Pack Lave',750,'LAVE'],['obstacle','tech','Pack Tech',950,'TECH'],['obstacle','ghost','Pack Fantome',1250,'FANTOME']];
const costs={distance:[250,500,900,1400,2100],dash:[300,650,1100,1700,2600],jump:[220,450,800,1250,1900],coin:[300,650,1050,1550,2300],bonus:[350,700,1100,1650,2500],lives:[500,900,1400,2100]};
function msg(t,e=false){$('authMsg').textContent=t;$('authMsg').style.color=e?'#ff7890':'#8ff7be'}function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');clearTimeout(toast.x);toast.x=setTimeout(()=>$('toast').classList.add('hidden'),2200)}
function email(u){return u.toLowerCase().replace(/[^a-z0-9_-]/g,'')+'@illegal-runner.local'}
async function register(){const u=$('username').value.trim().replace(/[^a-zA-Z0-9_-]/g,'').slice(0,18),p=$('password').value;if(u.length<3)return msg('Pseudo de 3 caracteres minimum.',true);if(p.length<6)return msg('Mot de passe de 6 caracteres minimum.',true);msg('Creation...');const r=await sb.auth.signUp({email:email(u),password:p,options:{data:{username:u}}});if(r.error)return msg(r.error.message,true);if(r.data.session)boot(r.data.user);else msg('Compte cree. Desactive la confirmation email dans Supabase.')}
async function login(){const u=$('username').value.trim(),p=$('password').value;if(!u||!p)return msg('Entre ton pseudo et ton mot de passe.',true);msg('Connexion...');const r=await sb.auth.signInWithPassword({email:email(u),password:p});if(r.error)return msg(r.error.message,true);boot(r.data.user)}
async function boot(user){st.user=user;$('authScreen').classList.add('hidden');$('mainApp').classList.remove('hidden');await load();show('play')}
async function load(){let r=await sb.from('profiles').select('*').eq('id',st.user.id).single();if(r.error){toast('Profil introuvable');return}st.p=r.data;let i=await sb.from('inventory').select('*').eq('user_id',st.user.id);st.inv=i.data||[];daily();render()}
async function daily(){if(!st.p)return;const d=new Date().toISOString().slice(0,10);if(st.p.last_login_reward===d)return;const reward=250+Math.min(7,(st.p.daily_login_streak||0)+1)*50;const c=await coins(reward);if(c){const upd={last_login_reward:d,daily_login_streak:(st.p.daily_login_streak||0)+1};await sb.from('profiles').update(upd).eq('id',st.p.id);Object.assign(st.p,upd);toast('Bonus quotidien +'+reward+' pieces')}}
async function coins(n){const r=await sb.rpc('change_coins',{amount:n});if(r.error){toast(r.error.message);return false}st.p.coins=Number(r.data);renderTop();return true}
function owned(type,id){return st.inv.some(x=>x.item_type===type&&x.item_id===id)}
async function buyPack(type,id,name,cost){if(Number(st.p.coins)<cost)return toast('Pas assez de pieces');if(!(await coins(-cost)))return;const r=await sb.from('inventory').insert({user_id:st.user.id,item_type:type,item_id:id});if(r.error){await coins(cost);return toast(r.error.message)}st.inv.push({item_type:type,item_id:id});toast(name+' debloque');render()}
async function upgrade(k){const l=Number(st.p[k+'_level']||1),max=k==='lives'?5:6;if(l>=max)return toast('MAX');const c=costs[k][l-1];if(Number(st.p.coins)<c)return toast('Pas assez de pieces');if(!(await coins(-c)))return;const u={};u[k+'_level']=l+1;const r=await sb.from('profiles').update(u).eq('id',st.p.id);if(r.error){await coins(c);return toast(r.error.message)}Object.assign(st.p,u);toast('Upgrade '+k+' niveau '+(l+1));render()}
function renderTop(){$('coins').textContent=Math.floor(st.p.coins);$('best').textContent=st.p.best_distance||0;document.querySelectorAll('.coinsText').forEach(x=>x.textContent=Math.floor(st.p.coins));$('streak').textContent=st.p.daily_login_streak||0;$('adminNav').classList.toggle('hidden',st.p.username!==ADMIN_USERNAME)}
function render(){if(!st.p)return;renderTop();renderUpgrades();renderPacks();renderProfile();renderQuests();renderLevels()}
function renderUpgrades(){const a=[['distance','Distance','Augmente la distance'],['dash','Dash','Niveau 6 = bouclier'],['jump','Saut','Ameliore le controle'],['coin','Pieces','Plus de pieces'],['bonus','Bonus','Jusqu a 10 secondes'],['lives','Vies','Jusqu a 5 vies']];$('upgradeGrid').innerHTML=a.map(x=>{const l=Number(st.p[x[0]+'_level']||1),m=x[0]==='lives'?5:6,c=l<m?costs[x[0]][l-1]:0;return `<div class="upgrade"><b>${x[1]}</b><div class="small">${x[2]}</div><div class="bar"><span style="width:${l/m*100}%"></span></div><div class="row"><span>Niv ${l}/${m}</span><button class="btn" ${l>=m?'disabled':''} onclick="upgrade('${x[0]}')">${l>=m?'MAX':' '+c+' pieces'}</button></div></div>`}).join('')}
function renderPacks(){ $('packGrid').innerHTML=packs.map(x=>`<div class="shop-card"><div class="shop-art">${x[4]}</div><div class="shop-name">${x[2]}</div><div class="price">${x[3]} pieces</div><button class="btn" ${owned(x[0],x[1])?'disabled':''} onclick="buyPack('${x[0]}','${x[1]}','${x[2]}',${x[3]})">${owned(x[0],x[1])?'Obtenu':'Ouvrir'}</button></div>`).join('');$('collectionGrid').innerHTML=st.inv.map(x=>`<div class="shop-card"><div class="shop-art">${x.item_id.toUpperCase()}</div><div class="shop-name">${x.item_id}</div><div class="small">${x.item_type}</div><button class="btn secondary" onclick="equip('${x.item_type}','${x.item_id}')">Equiper</button></div>`).join('')}
async function equip(type,id){const key=type==='background'?'selected_background':type==='character'?'selected_character':'selected_obstacle_set',u={};u[key]=id;const r=await sb.from('profiles').update(u).eq('id',st.p.id);if(r.error)return toast(r.error.message);st.p[key]=id;toast('Equipe')}
function renderProfile(){$('profileBox').innerHTML=`<div class="cards"><div class="quest">Pseudo<br><b>${st.p.username}</b></div><div class="quest">Pieces<br><b>${st.p.coins}</b></div><div class="quest">Record<br><b>${st.p.best_distance} m</b></div><div class="quest">Distance totale<br><b>${st.p.total_distance} m</b></div></div>`}
function renderQuests(){const p=st.p;const q=[['distance','Parcourir 1000 m',p.quest_distance||0,1000,200],['coins','Recuperer 100 pieces',p.quest_coins||0,100,150],['games','Faire 3 runs',p.quest_games||0,3,250]];$('questList').innerHTML=q.map(x=>`<div class="quest"><b>${x[1]}</b><p>${Math.min(x[2],x[3])}/${x[3]} · ${x[4]} pieces</p><div class="progress"><span style="width:${Math.min(100,x[2]/x[3]*100)}%"></span></div><button class="btn" onclick="claim('${x[0]}')">Reclamer</button></div>`).join('')}
async function claim(k){const p=st.p;const vals={distance:[p.quest_distance||0,1000,200],coins:[p.quest_coins||0,100,150],games:[p.quest_games||0,3,250]}[k];const flag='quest_'+k+'_claimed';if(vals[0]<vals[1]||p[flag])return toast('Quete pas terminee');const u={};u[flag]=true;await sb.from('profiles').update(u).eq('id',p.id);p[flag]=true;await coins(vals[2]);toast('Quete terminee')}
function renderLevels(){$('levelGrid').innerHTML=Array.from({length:300},(_,i)=>{const n=i+1,lock=n>(st.p.highest_level||1)+1;return `<button class="level ${lock?'lock':''}" ${lock?'disabled':''} onclick="selectLevel(${n})">${n}</button>`}).join('')}
function selectLevel(n){st.level=n;st.mode='level';$('modeLabel').textContent='Niveau '+n;$('sideLevel').textContent=n;startCountdown()}
function show(page){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('page-'+page).classList.remove('hidden');document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page))}
$('nav').onclick=e=>{const b=e.target.closest('button[data-page]');if(b)show(b.dataset.page)};$('loginBtn').onclick=login;$('registerBtn').onclick=register;$('logoutBtn').onclick=()=>sb.auth.signOut().then(()=>location.reload());$('loginReward').onclick=daily;$('infiniteBtn').onclick=()=>{st.mode='infinite';$('levelPicker').classList.add('hidden');$('modeLabel').textContent='Infini';startCountdown()};$('levelsBtn').onclick=()=>{$('levelPicker').classList.remove('hidden');st.mode='level';$('modeLabel').textContent='Niveau '+st.level};$('replayBtn').onclick=()=>{$('deathModal').classList.add('hidden');startCountdown()};$('closeDeath').onclick=()=>{$('deathModal').classList.add('hidden');show('play')};

const cv=document.getElementById('game'),ctx=cv.getContext('2d');let press=false;let engine={};function startCountdown(){if(running)return;let n=3;$('countNum').textContent=n;$('countdown').classList.remove('hidden');const id=setInterval(()=>{n--;if(!n){clearInterval(id);$('countdown').classList.add('hidden');startGame()}else $('countNum').textContent=n},500)}
function startGame(){running=true;runCoins=0;dashReady=0;engine={t:0,dist:0,speed:260+(st.mode==='level'?st.level*5:0),lives:Number(st.p.lives_level||1),p:{x:150,y:390,vy:0,w:42,h:60,inv:0,dash:0},objs:[],spawn:0,coin:0,bonus:null,bonusEnd:0};last=performance.now();requestAnimationFrame(frame)}
function jump(){if(!running)return;let p=engine.p;if(p.y+p.h>=cv.height-95){p.vy=-620-(Number(st.p.jump_level||1)-1)*20}else if(press&&p.vy>0)p.vy-=900/60}
function dash(){if(!running||performance.now()<dashReady)return;dashReady=performance.now()+20000;engine.p.dash=900;engine.p.inv=900}
$('jumpBtn').onpointerdown=()=>{press=true;jump()};['pointerup','pointercancel','pointerleave'].forEach(e=>$('jumpBtn').addEventListener(e,()=>press=false));$('dashBtn').onclick=dash;addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();press=true;jump()}if(e.code==='ShiftLeft'||e.code==='ShiftRight')dash()});addEventListener('keyup',e=>{if(e.code==='Space')press=false});
function spawn(type){const h=cv.height;engine.objs.push(type==='coin'?{x:1000,y:100+Math.random()*260,w:22,h:22,t:'coin'}:{x:1000,y:type==='flying'?120+Math.random()*210:h-150,w:type==='car'?100:48,h:type==='wall'?90:55,t:type});}
function rect(a,b){return a.x<a.x+a.w&&a.x+a.w>b.x&&a.y<a.y+a.h&&a.y+a.h>b.y}
function frame(now){if(!running)return;const dt=Math.min(.035,(now-last)/1000);last=now;engine.t+=dt;engine.dist+=engine.speed*dt/10;engine.spawn+=dt;engine.coin+=dt;const p=engine.p;p.vy+=1500*dt;if(press&&p.vy>0&&p.y+p.h<cv.height-95)p.vy-=1000*dt;p.y+=p.vy*dt;if(p.y+p.h>=cv.height-95){p.y=cv.height-95-p.h;p.vy=0}if(engine.spawn>.75){const a=['spike','wall','enemy','projectile','car','flying'];spawn(a[Math.floor(Math.random()*a.length)]);engine.spawn=0}if(engine.coin>.45){spawn('coin');engine.coin=0}p.inv=Math.max(0,p.inv-dt*1000);p.dash=Math.max(0,p.dash-dt*1000);if(p.dash>0&&st.p.dash_level>=6)p.inv=100;for(const o of engine.objs){o.x-=engine.speed*dt;if(o.t==='coin'){if(rect(p,o)){const mult=engine.bonus==='coins'&&performance.now()<engine.bonusEnd?2:1;runCoins+=mult; o.dead=1}}else if(rect(p,o)&&!o.dead){if(p.inv<=0){engine.lives--;p.inv=1100;if(engine.lives<=0){endRun();break}}o.dead=1}}engine.objs=engine.objs.filter(o=>!o.dead&&o.x>-150);$('distance').textContent=Math.floor(engine.dist);$('sideDistance').textContent=Math.floor(engine.dist);$('runCoins').textContent=runCoins;$('sideCoins').textContent=runCoins;$('lives').textContent=engine.lives;let cd=Math.max(0,(dashReady-performance.now())/1000);$('dashText').textContent=cd?cd.toFixed(1)+'s':'PRET';$('dashCd').textContent=cd?cd.toFixed(1)+'s':'PRET';draw(now);if(st.mode==='level'&&engine.dist>=500+(st.level-1)*35){finishLevel();return}requestAnimationFrame(frame)}
function draw(now){const w=cv.width,h=cv.height,bg=st.p.selected_background||'city';const g=ctx.createLinearGradient(0,0,0,h);if(bg==='forest'){g.addColorStop(0,'#173d34');g.addColorStop(1,'#081813')}else if(bg==='desert'){g.addColorStop(0,'#d68c4f');g.addColorStop(1,'#5b281a')}else if(bg==='space'){g.addColorStop(0,'#17104b');g.addColorStop(1,'#030412')}else if(bg==='dark'){g.addColorStop(0,'#25243b');g.addColorStop(1,'#05050d')}else{g.addColorStop(0,'#418bb3');g.addColorStop(1,'#101e35')}ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.fillStyle='rgba(255,255,255,.2)';for(let i=0;i<55;i++)ctx.fillRect((i*173-now*.05)%w,(i*79)%300,2,2);ctx.fillStyle='#172534';ctx.fillRect(0,h-95,w,95);ctx.fillStyle='#2c4153';ctx.fillRect(0,h-98,w,5);for(const o of engine.objs){if(o.t==='coin'){ctx.fillStyle='#ffd34d';ctx.beginPath();ctx.arc(o.x+11,o.y+11,11,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle=o.t==='spike'?'#e8edf2':o.t==='wall'?'#b14b68':o.t==='enemy'?'#ff637d':o.t==='projectile'?'#ffd34d':o.t==='car'?'#6b8cff':'#ab7bff';ctx.fillRect(o.x,o.y,o.w,o.h)}}const p=engine.p;ctx.save();if(p.inv>0&&Math.floor(p.inv/80)%2===0)ctx.globalAlpha=.45;ctx.fillStyle=st.p.selected_character==='ninja'?'#222':st.p.selected_character==='robot'?'#c8d3de':st.p.selected_character==='alien'?'#63f37d':st.p.selected_character==='fire'?'#ff7138':'#39e7ff';ctx.beginPath();ctx.arc(p.x+21,p.y+15,15,0,Math.PI*2);ctx.fill();ctx.fillRect(p.x+7,p.y+29,28,29);if(p.dash>0){ctx.strokeStyle='#6ff4ff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(p.x+21,p.y+30,42,0,Math.PI*2);ctx.stroke()}ctx.restore()}
async function saveRun(dist,coinsGot){const r=await sb.rpc('finish_run',{p_mode:st.mode,p_level:st.mode==='level'?st.level:0,p_distance:dist,p_coins:coinsGot,p_seconds:Math.floor(engine.t)});if(!r.error&&r.data){st.p.best_distance=Math.max(Number(st.p.best_distance||0),Number(r.data.best_distance||0));st.p.quest_distance=Number(r.data.quest_distance||st.p.quest_distance||0);st.p.quest_coins=Number(r.data.quest_coins||st.p.quest_coins||0);st.p.quest_games=Number(r.data.quest_games||st.p.quest_games||0)}await coins(coinsGot)}
async function endRun(){if(!running)return;running=false;const d=Math.floor(engine.dist),c=Math.floor(runCoins);await saveRun(d,c);$('deathTitle').textContent='Run terminee';$('finalDistance').textContent=d+' m';$('finalCoins').textContent=c;$('finalBest').textContent=st.p.best_distance;$('deathModal').classList.remove('hidden');render()}
async function finishLevel(){if(!running)return;running=false;const d=Math.floor(engine.dist),c=Math.floor(runCoins+100+st.level*15);await saveRun(d,c);const next=Math.min(300,Math.max(Number(st.p.highest_level||1),st.level+1));st.p.highest_level=next;await sb.from('profiles').update({highest_level:next}).eq('id',st.p.id);$('deathTitle').textContent='Niveau termine';$('finalDistance').textContent=d+' m';$('finalCoins').textContent=c;$('finalBest').textContent=st.p.best_distance;$('deathModal').classList.remove('hidden');render()}
$('adminSearchBtn').onclick=async()=>{if(st.p.username!==ADMIN_USERNAME)return toast('Acces refuse');const q=$('adminSearch').value.trim();const r=await sb.from('profiles').select('id,username,coins,best_distance').ilike('username','%'+q+'%').limit(20);if(r.error)return toast(r.error.message);$('adminResults').innerHTML=(r.data||[]).map(u=>`<div class="admin-user"><div><b>${u.username}</b><div class="small">${u.coins} pieces · ${u.best_distance} m</div></div><div class="row"><button class="btn gold" onclick="adminAdd('${u.id}',100)">+100</button><button class="btn" onclick="adminAdd('${u.id}',1000)">+1000</button></div></div>`).join('')||'<div class="small">Aucun utilisateur.</div>'};
async function adminAdd(id,n){if(st.p.username!==ADMIN_USERNAME)return toast('Acces refuse');const r=await sb.from('profiles').select('coins').eq('id',id).single();if(r.error)return toast(r.error.message);const u=await sb.from('profiles').update({coins:Number(r.data.coins)+n}).eq('id',id);if(u.error)return toast(u.error.message);toast('+'+n+' pieces');$('adminSearchBtn').click()}
window.upgrade=upgrade;window.buyPack=buyPack;window.equip=equip;window.claim=claim;window.selectLevel=selectLevel;window.adminAdd=adminAdd;
const session=await sb.auth.getSession();if(session.data.session)boot(session.data.session.user);