(() => {
'use strict'
const cfg=window.IR_CONFIG||{}
const sb=window.supabase&&cfg.SUPABASE_URL?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null
const S={
  user:null,requestId:null,sessionId:null,requestExpires:0,session:null,
  timer:null,pollTimer:null,syncTimer:null,nameMap:{},closed:false,renderedStatus:null,
  opponentId:null,opponentCharacter:'runner',ghostFrom:0,ghostTo:0,ghostStart:0,ghostDuration:450,ghostInitialized:false
}
const layer=document.createElement('div');layer.id='irDuelLayer';document.body.appendChild(layer)
const style=document.createElement('style');style.textContent='#irDuelLayer{position:fixed;inset:0;z-index:2147483590;display:none;align-items:center;justify-content:center;padding:16px;background:rgba(2,5,12,.9);backdrop-filter:blur(10px);font-family:Inter,system-ui,sans-serif}#irDuelLayer .dm{width:min(820px,96vw);max-height:94vh;overflow:auto;background:linear-gradient(145deg,#07101d,#030710);color:#f6fbff;border:1px solid rgba(0,229,255,.42);border-radius:22px;box-shadow:0 0 60px rgba(0,229,255,.14)}#irDuelLayer .dh{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:18px 20px;border-bottom:1px solid rgba(255,255,255,.08)}#irDuelLayer h2,#irDuelLayer h3{margin:0}#irDuelLayer .db{padding:18px}.duelCount{font-size:44px;font-weight:900;text-align:center;margin:10px 0;color:#00e5ff}.duelTimer{font-size:30px;font-weight:900;text-align:center;color:#ffd45c;margin:10px 0}.duelGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.duelCard{padding:14px;border:1px solid rgba(255,255,255,.08);border-radius:16px;background:rgba(255,255,255,.025)}#irDuelLayer .actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}#irDuelLayer button{border:1px solid #274765;background:#0d1929;color:#fff;border-radius:9px;padding:10px 13px;font-weight:900;cursor:pointer}#irDuelLayer button.primary{background:linear-gradient(90deg,#00a7cf,#d72583);border:0}#irDuelLayer button.danger{color:#ff9bb0;border-color:#633244;background:#1a0d15}.duelInfo{color:#93a0b6;font-size:13px}.duelVote{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.duelBetGrid{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.duelBetBtn{min-width:58px}.duelBetBtn.selected{background:linear-gradient(90deg,#007e9e,#81245b);border-color:#00e5ff}.duelResult{font-size:28px;font-weight:900;text-align:center;margin:18px 0}.duelHud{position:fixed;left:50%;top:12px;transform:translateX(-50%);z-index:2147483500;display:none;padding:9px 14px;border:1px solid rgba(0,229,255,.4);border-radius:13px;background:rgba(2,5,12,.86);color:#fff;font:900 14px Inter,sans-serif;box-shadow:0 0 18px rgba(0,229,255,.15);text-align:center}.duelHud .muted{opacity:.72}.duelHud button{margin-left:8px;border:1px solid #633244;background:#1a0d15;color:#ff9bb0;border-radius:7px;padding:5px 8px;font-weight:900}@media(max-width:700px){.duelGrid{grid-template-columns:1fr}.duelVote{grid-template-columns:1fr}.duelCount{font-size:36px}}';document.head.appendChild(style)
const hud=document.createElement('div');hud.className='duelHud';hud.id='irDuelHud';document.body.appendChild(hud)
function esc(v){return String(v??'').replace(/[&<>"']/g,function(x){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[x]})}
function show(html){layer.innerHTML=html;layer.style.display='flex'} function hide(){layer.style.display='none';clearTimers()} function clearTimers(){if(S.timer){clearInterval(S.timer);S.timer=null}} function toast(t){if(typeof window.toast==='function')window.toast(t);else alert(t)}
async function rpc(name,args){const r=await sb.rpc(name,args||{});if(r.error)throw r.error;return r.data}
function meA(s){return s&&s.user_a===S.user.id} function myField(s,a,b){return meA(s)?s[a]:s[b]} function otherId(s){return s?(meA(s)?s.user_b:s.user_a):null} function otherName(s){return esc((S.nameMap[otherId(s)]||'ton adversaire'))} function otherCharacter(s){return (meA(s)?s.character_b:s.character_a)||S.opponentCharacter||'runner'}
function ghostNow(){if(!S.ghostInitialized)return 0;const p=Math.max(0,Math.min(1,(performance.now()-S.ghostStart)/S.ghostDuration));return S.ghostFrom+(S.ghostTo-S.ghostFrom)*p} function syncGhost(s){const target=Number(meA(s)?s.distance_b:s.distance_a);if(!Number.isFinite(target))return;const now=performance.now();if(!S.ghostInitialized){S.ghostFrom=target;S.ghostTo=target;S.ghostStart=now;S.ghostDuration=0;S.ghostInitialized=true;return}const cur=ghostNow();if(Math.abs(target-S.ghostTo)>=1){S.ghostFrom=cur;S.ghostTo=target;S.ghostStart=now;S.ghostDuration=450}}
function remaining(until){if(!until)return 0;return Math.max(0,(new Date(until).getTime()-Date.now())/1000)} function goMenu(){hud.style.display='none';window.dispatchEvent(new CustomEvent('ir:duelExitToMenu'))} function stopGame(){const G=window.__IR_G;if(G){G.running=false;cancelAnimationFrame(G.raf)}}

async function refreshUser(){
  if(!sb)return
  const q=await sb.auth.getSession()
  S.user=q.data?.session?.user||null
  // À chaque nouvelle connexion/reconnexion, on nettoie les demandes 1V1
  // entrantes encore en attente. Cela empêche les anciennes demandes de
  // revenir en boucle après une reconnexion ou un rechargement.
  if(S.user){
    try{await rpc('duel_clear_incoming_requests')}catch(e){console.warn('[IR] nettoyage demandes 1V1:',e)}
  }
}
async function getRequests(){try{const data=await rpc('duel_poll_requests');const rows=Array.isArray(data)?data:[];rows.forEach(function(r){if(r.sender_id&&r.sender_username)S.nameMap[r.sender_id]=r.sender_username;if(r.receiver_id&&r.receiver_username)S.nameMap[r.receiver_id]=r.receiver_username});return rows}catch(_){if(!S.user)return[];const q=await sb.from('duel_requests').select('id,sender_id,receiver_id,status,created_at,expires_at').or('sender_id.eq.'+S.user.id+',receiver_id.eq.'+S.user.id).order('created_at',{ascending:false}).limit(20);return q.error?[]:(q.data||[])}}
async function getSession(){if(!S.sessionId)return null;try{const G=window.__IR_G;const distance=Math.max(0,Math.floor(Number(G?.dist||0)));const lives=Math.max(0,Math.floor(Number(G?.lives||0)));const player=G?.player;const action=G?.dashT>0?'dash':(player&&!player.ground?'jump':'run');const y=Number(player?.y);const jumpHeight=Number.isFinite(y)&&Number.isFinite(G?.groundY)&&Number.isFinite(G?.H)?Math.max(0,Math.min(1,(G.groundY-y)/G.H)):0;const data=await rpc('duel_tick',{p_session_id:S.sessionId,p_distance:distance,p_lives:lives,p_y:jumpHeight,p_action:action});S.session=data||null;return S.session}catch(e){const q=await sb.from('duel_sessions').select('*').eq('id',S.sessionId).maybeSingle();if(!q.error&&q.data){S.session=q.data;return q.data}return S.session}}

function requestGui(r){const requestId=String(r?.id||'');if(!requestId)return;S.requestId=requestId;S.requestExpires=r.expires_at?new Date(r.expires_at).getTime():Date.now()+30000;const incoming=r.receiver_id===S.user.id;const who=esc(incoming?(r.sender_username||'Ton ami'):(r.receiver_username||'Ton ami'));if(incoming){show('<div class="dm"><div class="dh"><h2>⚔️ Demande de 1V1</h2><button id="dx">✕</button></div><div class="db"><h3>👤 '+who+' veut faire un 1V1 avec toi.</h3><div class="duelTimer" id="rt"></div><p class="duelInfo">Tu as 30 secondes pour accepter.</p><div class="actions"><button class="primary" id="da">✅ ACCEPTER</button><button class="danger" id="dr">❌ REFUSER</button></div></div></div>');document.getElementById('da').onclick=function(){respondRequest(requestId,true)};document.getElementById('dr').onclick=function(){respondRequest(requestId,false)};document.getElementById('dx').onclick=function(){respondRequest(requestId,false)}}else{show('<div class="dm"><div class="dh"><h2>⚔️ 1V1 contre '+who+'</h2><button id="dx">✕</button></div><div class="db"><div class="duelCount">1 / 2</div><h3 style="text-align:center">⏳ En attente de '+who+'</h3><div class="duelTimer" id="rt"></div><p class="duelInfo" style="text-align:center">La demande a été envoyée.</p><div class="actions"><button class="danger" id="dc">❌ ANNULER</button></div></div></div>');document.getElementById('dc').onclick=function(){cancelRequest(requestId)};document.getElementById('dx').onclick=function(){cancelRequest(requestId)}}startRequestTimer()}
function startRequestTimer(){clearTimers();S.timer=setInterval(async function(){const e=document.getElementById('rt');const left=Math.ceil(Math.max(0,(S.requestExpires-Date.now())/1000));if(e)e.textContent=left+' s';if(left<=0){clearTimers();await cancelRequest(true)}},200)}
async function cancelRequest(requestIdOrSilent,silentMaybe){const silent=typeof requestIdOrSilent==='boolean'?requestIdOrSilent:!!silentMaybe;const requestId=typeof requestIdOrSilent==='string'?requestIdOrSilent:(S.requestId?String(S.requestId):'');try{if(requestId)await rpc('duel_cancel_request',{p_request_id:requestId})}catch(_){}if(!silent)toast('❌ Demande 1V1 annulée.');if(!requestId||String(S.requestId)===requestId)S.requestId=null;hide()}
async function respondRequest(requestIdOrOk,okMaybe){const ok=typeof requestIdOrOk==='boolean'?requestIdOrOk:!!okMaybe;const requestId=typeof requestIdOrOk==='string'?requestIdOrOk:(S.requestId?String(S.requestId):'');if(!requestId){alert('❌ Demande 1V1 introuvable.');return}const acceptBtn=document.getElementById('da'),rejectBtn=document.getElementById('dr'),closeBtn=document.getElementById('dx');if(acceptBtn)acceptBtn.disabled=true;if(rejectBtn)rejectBtn.disabled=true;if(closeBtn)closeBtn.disabled=true;try{const sid=await rpc('duel_respond_request',{p_request_id:requestId,p_accept:ok});if(!ok){S.requestId=null;hide();return}let resolvedSid=sid;if(!resolvedSid){const q=await sb.from('duel_sessions').select('id').eq('request_id',requestId).maybeSingle();resolvedSid=q.data?.id||null}if(!resolvedSid)throw new Error('La session 1V1 n’a pas pu être créée. Réessaie.');S.sessionId=resolvedSid;S.renderedStatus=null;const data=await getSession();S.requestId=null;sessionGui(data)}catch(e){if(acceptBtn)acceptBtn.disabled=false;if(rejectBtn)rejectBtn.disabled=false;if(closeBtn)closeBtn.disabled=false;alert('❌ '+(e.message||'Demande impossible'))}}

// Le reste du moteur 1V1 reste inchangé.
})();