create extension if not exists pgcrypto;

create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 username text not null unique,
 coins bigint not null default 0 check (coins >= 0),
 best_distance integer not null default 0,
 total_distance bigint not null default 0,
 highest_level integer not null default 1 check (highest_level between 1 and 300),
 selected_background text not null default 'city',
 selected_character text not null default 'runner',
 selected_obstacle_set text not null default 'classic',
 lives_level integer not null default 1 check (lives_level between 1 and 5),
 distance_level integer not null default 1 check (distance_level between 1 and 6),
 dash_level integer not null default 1 check (dash_level between 1 and 6),
 jump_level integer not null default 1 check (jump_level between 1 and 6),
 coin_level integer not null default 1 check (coin_level between 1 and 6),
 bonus_level integer not null default 1 check (bonus_level between 1 and 6),
 daily_login_streak integer not null default 0,
 last_login_reward date,
 last_quest_reset date,
 free_pack_date date,
 quest_distance integer not null default 0,
 quest_coins integer not null default 0,
 quest_games integer not null default 0,
 quest_distance_claimed boolean not null default false,
 quest_coins_claimed boolean not null default false,
 quest_games_claimed boolean not null default false,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists free_pack_date date;

create table if not exists public.inventory (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 item_type text not null check (item_type in ('background','character','obstacle')),
 item_id text not null,
 owned_at timestamptz not null default now(),
 unique(user_id,item_type,item_id)
);

create table if not exists public.run_history (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 mode text not null check (mode in ('infinite','level')),
 level_number integer,
 distance integer not null default 0,
 coins integer not null default 0,
 survived_seconds integer not null default 0,
 created_at timestamptz not null default now()
);

create table if not exists public.friends (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 friend_id uuid not null references public.profiles(id) on delete cascade,
 status text not null default 'accepted' check (status in ('pending','accepted','blocked')),
 created_at timestamptz not null default now(),
 unique(user_id,friend_id),
 check(user_id <> friend_id)
);

create table if not exists public.admin_gifts (
 id bigint generated by default as identity primary key,
 target_user uuid not null references public.profiles(id) on delete cascade,
 amount bigint not null check (amount > 0 and amount <= 1000000),
 created_by uuid not null references auth.users(id) on delete cascade,
 created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.inventory enable row level security;
alter table public.run_history enable row level security;
alter table public.friends enable row level security;
alter table public.admin_gifts enable row level security;

drop policy if exists profiles_select on public.profiles;
drop policy if exists profiles_insert on public.profiles;
drop policy if exists profiles_update on public.profiles;
drop policy if exists profiles_admin on public.profiles;
drop policy if exists inventory_select on public.inventory;
drop policy if exists inventory_insert on public.inventory;
drop policy if exists inventory_delete on public.inventory;
drop policy if exists runs_select on public.run_history;
drop policy if exists runs_insert on public.run_history;
drop policy if exists friends_select on public.friends;
drop policy if exists friends_insert on public.friends;
drop policy if exists friends_update on public.friends;
drop policy if exists friends_delete on public.friends;
drop policy if exists gifts_admin on public.admin_gifts;

create policy profiles_select on public.profiles for select using (auth.uid()=id or lower(coalesce(auth.jwt()->>'email',''))='rubansu1@illegal-runner.local');
create policy profiles_insert on public.profiles for insert with check (auth.uid()=id);
create policy profiles_update on public.profiles for update using (auth.uid()=id) with check (auth.uid()=id);
create policy profiles_admin on public.profiles for all using (lower(coalesce(auth.jwt()->>'email',''))='rubansu1@illegal-runner.local') with check (lower(coalesce(auth.jwt()->>'email',''))='rubansu1@illegal-runner.local');
create policy inventory_select on public.inventory for select using (auth.uid()=user_id);
create policy inventory_insert on public.inventory for insert with check (auth.uid()=user_id);
create policy inventory_delete on public.inventory for delete using (auth.uid()=user_id);
create policy runs_select on public.run_history for select using (auth.uid()=user_id);
create policy runs_insert on public.run_history for insert with check (auth.uid()=user_id);
create policy friends_select on public.friends for select using (auth.uid()=user_id or auth.uid()=friend_id);
create policy friends_insert on public.friends for insert with check (auth.uid()=user_id);
create policy friends_update on public.friends for update using (auth.uid()=user_id or auth.uid()=friend_id) with check (auth.uid()=user_id or auth.uid()=friend_id);
create policy friends_delete on public.friends for delete using (auth.uid()=user_id or auth.uid()=friend_id);
create policy gifts_admin on public.admin_gifts for insert with check (created_by=auth.uid() and lower(coalesce(auth.jwt()->>'email',''))='rubansu1@illegal-runner.local');

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
 insert into public.profiles(id,username) values(new.id,coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1))) on conflict(id) do nothing;
 return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.give_default_items()
returns trigger language plpgsql security definer set search_path=public as $$
begin
 insert into public.inventory(user_id,item_type,item_id) values (new.id,'background','city'),(new.id,'character','runner'),(new.id,'obstacle','classic') on conflict do nothing;
 return new;
end;
$$;
drop trigger if exists on_profile_created_items on public.profiles;
create trigger on_profile_created_items after insert on public.profiles for each row execute procedure public.give_default_items();

create or replace function public.change_coins(amount bigint)
returns bigint language plpgsql security invoker as $$
declare b bigint;
begin update public.profiles set coins=greatest(0,coins+amount),updated_at=now() where id=auth.uid() returning coins into b; if b is null then raise exception 'Profile not found'; end if; return b; end;
$$;

create or replace function public.finish_run(p_mode text,p_level integer,p_distance integer,p_coins integer,p_seconds integer,p_highest_level integer)
returns jsonb language plpgsql security invoker set search_path=public as $$
declare b integer; td bigint; c bigint; qd integer; qc integer; qg integer; hl integer;
begin
 update public.profiles
 set coins=coins+greatest(0,p_coins),
     best_distance=greatest(best_distance,greatest(0,p_distance)),
     total_distance=total_distance+greatest(0,p_distance),
     highest_level=greatest(highest_level,least(300,greatest(1,p_highest_level))),
     quest_distance=quest_distance+greatest(0,p_distance),
     quest_coins=quest_coins+greatest(0,p_coins),
     quest_games=quest_games+1,
     updated_at=now()
 where id=auth.uid()
 returning best_distance,total_distance,coins,quest_distance,quest_coins,quest_games,highest_level into b,td,c,qd,qc,qg,hl;
 if b is null then raise exception 'Profile not found'; end if;
 insert into public.run_history(user_id,mode,level_number,distance,coins,survived_seconds)
 values(auth.uid(),p_mode,nullif(p_level,0),greatest(0,p_distance),greatest(0,p_coins),greatest(0,p_seconds));
 return jsonb_build_object('coins',c,'best_distance',b,'total_distance',td,'highest_level',hl,'quest_distance',qd,'quest_coins',qc,'quest_games',qg);
end;
$$;

drop function if exists public.finish_run(text,integer,integer,integer,integer);
grant execute on function public.finish_run(text,integer,integer,integer,integer,integer) to authenticated;

-- Classement complet pour tous les comptes connectés.
drop function if exists public.get_leaderboard();

create or replace function public.get_leaderboard()
returns table(
 username text,
 best_distance integer,
 highest_level integer
)
language sql
security definer
set search_path=public
as $$
 select p.username,p.best_distance,p.highest_level
 from public.profiles p
 order by p.best_distance desc,p.highest_level desc,p.username asc;
$$;

revoke all on function public.get_leaderboard() from public;
grant execute on function public.get_leaderboard() to authenticated;


create or replace function public.buy_pack(p_type text)
returns jsonb language plpgsql security invoker set search_path=public as $$
declare cost bigint; chosen text; reward integer; uid uuid := auth.uid();
declare ids text[];
begin
 if uid is null then raise exception 'Not authenticated'; end if;
 if p_type='world' then cost:=250; ids:=array['city','forest','desert','space','dark','volcano','ice'];
 elsif p_type='character' then cost:=200; ids:=array['runner','ninja','robot','ghost','cyber'];
 elsif p_type='obstacle' then cost:=180; ids:=array['classic','tech','drone','energy','chaos'];
 elsif p_type='reward' then cost:=300;
 else raise exception 'Invalid pack'; end if;
 if p_type='reward' then
   reward:=100+floor(random()*651)::integer;
   update public.profiles set coins=coins-cost+reward,updated_at=now() where id=uid and coins>=cost;
   if not found then raise exception 'Not enough coins'; end if;
   return jsonb_build_object('reward',reward);
 end if;
 select i.id into chosen from unnest(ids) as i(id)
 where not exists(select 1 from public.inventory x where x.user_id=uid and x.item_type=case when p_type='world' then 'background' when p_type='character' then 'character' else 'obstacle' end and x.item_id=i.id)
 order by random() limit 1;
 if chosen is null then raise exception 'Everything already unlocked'; end if;
 update public.profiles set coins=coins-cost,updated_at=now() where id=uid and coins>=cost;
 if not found then raise exception 'Not enough coins'; end if;
 insert into public.inventory(user_id,item_type,item_id) values(uid,case when p_type='world' then 'background' when p_type='character' then 'character' else 'obstacle' end,chosen);
 return jsonb_build_object('item_id',chosen,'type',p_type);
end;
$$;
grant execute on function public.buy_pack(text) to authenticated;

create or replace function public.claim_free_pack()
returns bigint language plpgsql security invoker set search_path=public as $$
declare today date:=current_date; newcoins bigint;
begin
 update public.profiles set coins=coins+75,free_pack_date=today,updated_at=now() where id=auth.uid() and (free_pack_date is null or free_pack_date<>today) returning coins into newcoins;
 if newcoins is null then raise exception 'Already claimed today'; end if;
 return newcoins;
end;
$$;
grant execute on function public.claim_free_pack() to authenticated;

create or replace function public.apply_admin_gift()
returns trigger language plpgsql security definer set search_path=public as $$
begin
 update public.profiles set coins=coins+new.amount,updated_at=now() where id=new.target_user;
 return new;
end;
$$;
drop trigger if exists on_admin_gift on public.admin_gifts;
create trigger on_admin_gift after insert on public.admin_gifts for each row execute procedure public.apply_admin_gift();

create index if not exists profiles_username_idx on public.profiles(username);
create index if not exists profiles_best_idx on public.profiles(best_distance desc);
create index if not exists inventory_user_idx on public.inventory(user_id);
create index if not exists run_history_user_idx on public.run_history(user_id,created_at desc);
create index if not exists friends_user_idx on public.friends(user_id);
create index if not exists friends_friend_idx on public.friends(friend_id);
create index if not exists admin_gifts_target_idx on public.admin_gifts(target_user,created_at desc);
