create extension if not exists pgcrypto;

create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 username text not null unique,
 coins bigint not null default 0 check (coins >= 0),
 best_distance integer not null default 0,
 total_distance bigint not null default 0,
 highest_level integer not null default 1 check (highest_level between 1 and 300),
 selected_background text not null default 'city',
 selected_character text not null default 'runner',
 selected_obstacle_set text not null default 'classic',
 lives_level integer not null default 1 check (lives_level between 1 and 5),
 distance_level integer not null default 1 check (distance_level between 1 and 6),
 dash_level integer not null default 1 check (dash_level between 1 and 6),
 jump_level integer not null default 1 check (jump_level between 1 and 6),
 coin_level integer not null default 1 check (coin_level between 1 and 6),
 bonus_level integer not null default 1 check (bonus_level between 1 and 6),
 daily_login_streak integer not null default 0,
 last_login_reward date,
 last_quest_reset date,
 free_pack_date date,
 quest_distance integer not null default 0,
 quest_coins integer not null default 0,
 quest_games integer not null default 0,
 quest_distance_claimed boolean not null default false,
 quest_coins_claimed boolean not null default false,
 quest_games_claimed boolean not null default false,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists free_pack_date date;
alter table public.profiles add column if not exists bonus_mega_level integer not null default 1 check (bonus_mega_level between 1 and 6);
alter table public.profiles add column if not exists bonus_x2_level integer not null default 1 check (bonus_x2_level between 1 and 6);
alter table public.profiles add column if not exists bonus_shield_level integer not null default 1 check (bonus_shield_level between 1 and 6);
alter table public.profiles add column if not exists bonus_jetpack_level integer not null default 1 check (bonus_jetpack_level between 1 and 6);
alter table public.profiles add column if not exists bonus_scoreDouble_level integer not null default 1 check (bonus_scoreDouble_level between 1 and 6);
alter table public.profiles add column if not exists bonus_magnet_level integer not null default 1 check (bonus_magnet_level between 1 and 6);

create table if not exists public.inventory (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 item_type text not null check (item_type in ('background','character','obstacle')),
 item_id text not null,
 owned_at timestamptz not null default now(),
 unique(user_id,item_type,item_id)
);

create table if not exists public.run_history (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 mode text not null check (mode in ('infinite','level')),
 level_number integer,
 distance integer not null default 0,
 coins integer not null default 0,
 survived_seconds integer not null default 0,
 created_at timestamptz not null default now()
);

create table if not exists public.friends (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 friend_id uuid not null references public.profiles(id) on delete cascade,
 status text not null default 'accepted' check (status in ('pending','accepted','blocked')),
 created_at timestamptz not null default now(),
 unique(user_id,friend_id),
 check(user_id <> friend_id)
);

create table if not exists public.admin_gifts (
 id bigint generated by default as identity primary key,
 target_user uuid not null references public.profiles(id) on delete cascade,
 amount bigint not null check (amount > 0 and amount <= 1000000),
 created_by uuid not null references auth.users(id) on delete cascade,
 created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.inventory enable row level security;
alter table public.run_history enable row level security;
alter table public.friends enable row level security;
alter table public.admin_gifts enable row level security;

drop policy if exists profiles_select on public.profiles;
drop policy if exists profiles_insert on public.profiles;
drop policy if exists profiles_update on public.profiles;
drop policy if exists profiles_admin on public.profiles;
drop policy if exists inventory_select on public.inventory;
drop policy if exists inventory_insert on public.inventory;
drop policy if exists inventory_delete on public.inventory;
drop policy if exists runs_select on public.run_history;
drop policy if exists runs_insert on public.run_history;
drop policy if exists friends_select on public.friends;
drop policy if exists friends_insert on public.friends;
drop policy if exists friends_update on public.friends;
drop policy if exists friends_delete on public.friends;
drop policy if exists gifts_admin on public.admin_gifts;

create policy profiles_select on public.profiles for select using (auth.uid()=id or lower(coalesce(auth.jwt()->>'email',''))='rubansu1@illegal-runner.local');
create policy profiles_insert on public.profiles for insert with check (auth.uid()=id);
create policy profiles_update on public.profiles for update using (auth.uid()=id) with check (auth.uid()=id);
create policy profiles_admin on public.profiles for all using (lower(coalesce(auth.jwt()->>'email',''))='rubansu1@illegal-runner.local') with check (lower(coalesce(auth.jwt()->>'email',''))='rubansu1@illegal-runner.local');
create policy inventory_select on public.inventory for select using (auth.uid()=user_id);
create policy inventory_insert on public.inventory for insert with check (auth.uid()=user_id);
create policy inventory_delete on public.inventory for delete using (auth.uid()=user_id);
create policy runs_select on public.run_history for select using (auth.uid()=user_id);
create policy runs_insert on public.run_history for insert with check (auth.uid()=user_id);
create policy friends_select on public.friends for select using (auth.uid()=user_id or auth.uid()=friend_id);
create policy friends_insert on public.friends for insert with check (auth.uid()=user_id);
create policy friends_update on public.friends for update using (auth.uid()=user_id or auth.uid()=friend_id) with check (auth.uid()=user_id or auth.uid()=friend_id);
create policy friends_delete on public.friends for delete using (auth.uid()=user_id or auth.uid()=friend_id);
create policy gifts_admin on public.admin_gifts for insert with check (created_by=auth.uid() and lower(coalesce(auth.jwt()->>'email',''))='rubansu1@illegal-runner.local');

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
 insert into public.profiles(id,username) values(new.id,coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1))) on conflict(id) do nothing;
 return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.give_default_items()
returns trigger language plpgsql security definer set search_path=public as $$
begin
 insert into public.inventory(user_id,item_type,item_id) values (new.id,'background','city'),(new.id,'character','runner'),(new.id,'obstacle','classic') on conflict do nothing;
 return new;
end;
$$;
drop trigger if exists on_profile_created_items on public.profiles;
create trigger on_profile_created_items after insert on public.profiles for each row execute procedure public.give_default_items();

create or replace function public.change_coins(amount bigint)
returns bigint language plpgsql security invoker as $$
declare b bigint;
begin update public.profiles set coins=greatest(0,coins+amount),updated_at=now() where id=auth.uid() returning coins into b; if b is null then raise exception 'Profile not found'; end if; return b; end;
$$;

create or replace function public.finish_run(p_mode text,p_level integer,p_distance integer,p_coins integer,p_seconds integer,p_highest_level integer)
returns jsonb language plpgsql security invoker set search_path=public as $$
declare b integer; td bigint; c bigint; qd integer; qc integer; qg integer; hl integer;
begin
 update public.profiles
 set coins=coins+greatest(0,p_coins),
     best_distance=greatest(best_distance,greatest(0,p_distance)),
     total_distance=total_distance+greatest(0,p_distance),
     highest_level=greatest(highest_level,least(300,greatest(1,p_highest_level))),
     quest_distance=quest_distance+greatest(0,p_distance),
     quest_coins=quest_coins+greatest(0,p_coins),
     quest_games=quest_games+1,
     updated_at=now()
 where id=auth.uid()
 returning best_distance,total_distance,coins,quest_distance,quest_coins,quest_games,highest_level into b,td,c,qd,qc,qg,hl;
 if b is null then raise exception 'Profile not found'; end if;
 insert into public.run_history(user_id,mode,level_number,distance,coins,survived_seconds)
 values(auth.uid(),p_mode,nullif(p_level,0),greatest(0,p_distance),greatest(0,p_coins),greatest(0,p_seconds));
 return jsonb_build_object('coins',c,'best_distance',b,'total_distance',td,'highest_level',hl,'quest_distance',qd,'quest_coins',qc,'quest_games',qg);
end;
$$;

drop function if exists public.finish_run(text,integer,integer,integer,integer);
grant execute on function public.finish_run(text,integer,integer,integer,integer,integer) to authenticated;

-- Classement complet pour tous les comptes connectés.
drop function if exists public.get_leaderboard();

create or replace function public.get_leaderboard()
returns table(
 username text,
 best_distance integer,
 highest_level integer
)
language sql
security definer
set search_path=public
as $$
 select p.username,p.best_distance,p.highest_level
 from public.profiles p
 order by p.best_distance desc,p.highest_level desc,p.username asc;
$$;

revoke all on function public.get_leaderboard() from public;
grant execute on function public.get_leaderboard() to authenticated;


create or replace function public.buy_pack(p_type text)
returns jsonb language plpgsql security invoker set search_path=public as $$
declare cost bigint; chosen text; reward integer; uid uuid := auth.uid();
declare ids text[];
begin
 if uid is null then raise exception 'Not authenticated'; end if;
 if p_type='world' then cost:=250; ids:=array['city','forest','desert','space','dark','volcano','ice'];
 elsif p_type='character' then cost:=200; ids:=array['runner','ninja','robot','ghost','cyber'];
 elsif p_type='obstacle' then cost:=180; ids:=array['classic','tech','drone','energy','chaos'];
 elsif p_type='reward' then cost:=300;
 else raise exception 'Invalid pack'; end if;
 if p_type='reward' then
   reward:=100+floor(random()*651)::integer;
   update public.profiles set coins=coins-cost+reward,updated_at=now() where id=uid and coins>=cost;
   if not found then raise exception 'Not enough coins'; end if;
   return jsonb_build_object('reward',reward);
 end if;
 select i.id into chosen from unnest(ids) as i(id)
 where not exists(select 1 from public.inventory x where x.user_id=uid and x.item_type=case when p_type='world' then 'background' when p_type='character' then 'character' else 'obstacle' end and x.item_id=i.id)
 order by random() limit 1;
 if chosen is null then raise exception 'Everything already unlocked'; end if;
 update public.profiles set coins=coins-cost,updated_at=now() where id=uid and coins>=cost;
 if not found then raise exception 'Not enough coins'; end if;
 insert into public.inventory(user_id,item_type,item_id) values(uid,case when p_type='world' then 'background' when p_type='character' then 'character' else 'obstacle' end,chosen);
 return jsonb_build_object('item_id',chosen,'type',p_type);
end;
$$;
grant execute on function public.buy_pack(text) to authenticated;

create or replace function public.claim_free_pack()
returns bigint language plpgsql security invoker set search_path=public as $$
declare today date:=current_date; newcoins bigint;
begin
 update public.profiles set coins=coins+75,free_pack_date=today,updated_at=now() where id=auth.uid() and (free_pack_date is null or free_pack_date<>today) returning coins into newcoins;
 if newcoins is null then raise exception 'Already claimed today'; end if;
 return newcoins;
end;
$$;
grant execute on function public.claim_free_pack() to authenticated;

create or replace function public.apply_admin_gift()
returns trigger language plpgsql security definer set search_path=public as $$
begin
 update public.profiles set coins=coins+new.amount,updated_at=now() where id=new.target_user;
 return new;
end;
$$;
drop trigger if exists on_admin_gift on public.admin_gifts;
create trigger on_admin_gift after insert on public.admin_gifts for each row execute procedure public.apply_admin_gift();

create index if not exists profiles_username_idx on public.profiles(username);
create index if not exists profiles_best_idx on public.profiles(best_distance desc);
create index if not exists inventory_user_idx on public.inventory(user_id);
create index if not exists run_history_user_idx on public.run_history(user_id,created_at desc);
create index if not exists friends_user_idx on public.friends(user_id);
create index if not exists friends_friend_idx on public.friends(friend_id);
create index if not exists admin_gifts_target_idx on public.admin_gifts(target_user,created_at desc);

-- ============================================================
-- ILLEGAL RUNNER — ÉCHANGES ENTRE AMIS
-- ============================================================

alter table public.inventory drop constraint if exists inventory_item_type_check;
alter table public.inventory add column if not exists quantity integer not null default 1;
alter table public.inventory add constraint inventory_item_type_check
  check (item_type in ('background','character','obstacle','coin'));
update public.inventory set quantity=1 where quantity is null or quantity < 1;

create table if not exists public.trade_requests (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check(status in ('pending','accepted','declined','cancelled','completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check(sender_id <> receiver_id)
);

create table if not exists public.trade_sessions (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null unique references public.trade_requests(id) on delete cascade,
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'open' check(status in ('open','countdown','completed','cancelled')),
  offer_a_coins bigint not null default 0 check(offer_a_coins >= 0),
  offer_b_coins bigint not null default 0 check(offer_b_coins >= 0),
  accepted_a boolean not null default false,
  accepted_b boolean not null default false,
  confirmed_a boolean not null default false,
  confirmed_b boolean not null default false,
  countdown_started_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check(user_a <> user_b)
);

create table if not exists public.trade_items (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.trade_sessions(id) on delete cascade,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  item_type text not null check(item_type in ('background','character','obstacle','coin')),
  item_id text not null,
  quantity integer not null check(quantity > 0),
  unique(session_id,owner_id,item_type,item_id)
);

create table if not exists public.trade_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.trade_sessions(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  message text not null check(char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.trade_requests enable row level security;
alter table public.trade_sessions enable row level security;
alter table public.trade_items enable row level security;
alter table public.trade_messages enable row level security;

drop policy if exists trade_requests_select on public.trade_requests;
drop policy if exists trade_sessions_select on public.trade_sessions;
drop policy if exists trade_items_select on public.trade_items;
drop policy if exists trade_messages_select on public.trade_messages;

create policy trade_requests_select on public.trade_requests
for select using (auth.uid()=sender_id or auth.uid()=receiver_id);

create policy trade_sessions_select on public.trade_sessions
for select using (auth.uid()=user_a or auth.uid()=user_b);

create policy trade_items_select on public.trade_items
for select using (
  exists(select 1 from public.trade_sessions s
    where s.id=trade_items.session_id and (s.user_a=auth.uid() or s.user_b=auth.uid()))
);

create policy trade_messages_select on public.trade_messages
for select using (
  exists(select 1 from public.trade_sessions s
    where s.id=trade_messages.session_id and (s.user_a=auth.uid() or s.user_b=auth.uid()))
);

create index if not exists trade_requests_participants_idx on public.trade_requests(sender_id,receiver_id,status);
create index if not exists trade_sessions_participants_idx on public.trade_sessions(user_a,user_b,status);
create index if not exists trade_items_session_idx on public.trade_items(session_id,owner_id);
create index if not exists trade_messages_session_idx on public.trade_messages(session_id,created_at);

create or replace function public.trade_create_request(p_friend_id uuid)
returns uuid language plpgsql security definer set search_path=public as $$
declare rid uuid;
begin
  if p_friend_id is null or p_friend_id=auth.uid() then raise exception 'Invalid friend'; end if;
  if not exists (
    select 1 from public.friends f
    where f.status='accepted' and
      ((f.user_id=auth.uid() and f.friend_id=p_friend_id)
       or (f.user_id=p_friend_id and f.friend_id=auth.uid()))
  ) then raise exception 'You are not friends'; end if;
  select id into rid from public.trade_requests
  where status='pending' and
    ((sender_id=auth.uid() and receiver_id=p_friend_id)
     or (sender_id=p_friend_id and receiver_id=auth.uid()))
  order by created_at desc limit 1;
  if rid is not null then return rid; end if;
  insert into public.trade_requests(sender_id,receiver_id) values(auth.uid(),p_friend_id) returning id into rid;
  return rid;
end;
$$;

create or replace function public.trade_respond_request(p_request_id uuid,p_accept boolean)
returns uuid language plpgsql security definer set search_path=public as $$
declare req public.trade_requests%rowtype; sid uuid;
begin
  select * into req from public.trade_requests
  where id=p_request_id and receiver_id=auth.uid() and status='pending' for update;
  if not found then raise exception 'Trade request not found'; end if;
  if not p_accept then
    update public.trade_requests set status='declined',updated_at=now() where id=req.id;
    return null;
  end if;
  insert into public.trade_sessions(request_id,user_a,user_b) values(req.id,req.sender_id,req.receiver_id) returning id into sid;
  update public.trade_requests set status='accepted',updated_at=now() where id=req.id;
  return sid;
end;
$$;

create or replace function public.trade_cancel_request(p_request_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  update public.trade_requests set status='cancelled',updated_at=now()
  where id=p_request_id and sender_id=auth.uid() and status='pending';
  return found;
end;
$$;

create or replace function public.trade_set_offer(p_session_id uuid,p_coins bigint,p_items jsonb)
returns boolean language plpgsql security definer set search_path=public as $$
declare s public.trade_sessions%rowtype; x jsonb; t text; iid text; qty integer; owned integer;
begin
  if p_coins is null or p_coins < 0 then raise exception 'Invalid coins'; end if;
  select * into s from public.trade_sessions where id=p_session_id and status='open' for update;
  if not found or (s.user_a<>auth.uid() and s.user_b<>auth.uid()) then raise exception 'Trade not available'; end if;
  if (select coins from public.profiles where id=auth.uid()) < p_coins then raise exception 'Not enough coins'; end if;
  if jsonb_typeof(coalesce(p_items,'[]'::jsonb)) <> 'array' then raise exception 'Invalid items'; end if;

  delete from public.trade_items where session_id=p_session_id and owner_id=auth.uid();
  for x in select * from jsonb_array_elements(coalesce(p_items,'[]'::jsonb)) loop
    t:=x->>'item_type'; iid:=x->>'item_id'; qty:=greatest(0,(x->>'quantity')::integer);
    if qty>0 then
      if t not in ('background','character','obstacle','coin') then raise exception 'Invalid item type'; end if;
      select quantity into owned from public.inventory
      where user_id=auth.uid() and item_type=t and item_id=iid;
      if coalesce(owned,0)<qty then raise exception 'Item quantity not owned'; end if;
      insert into public.trade_items(session_id,owner_id,item_type,item_id,quantity)
      values(p_session_id,auth.uid(),t,iid,qty);
    end if;
  end loop;

  if s.user_a=auth.uid() then
    update public.trade_sessions set offer_a_coins=p_coins,accepted_a=false,accepted_b=false,
      confirmed_a=false,confirmed_b=false,status='open',countdown_started_at=null,updated_at=now()
    where id=p_session_id;
  else
    update public.trade_sessions set offer_b_coins=p_coins,accepted_a=false,accepted_b=false,
      confirmed_a=false,confirmed_b=false,status='open',countdown_started_at=null,updated_at=now()
    where id=p_session_id;
  end if;
  return true;
end;
$$;

create or replace function public.trade_set_accepted(p_session_id uuid,p_accept boolean)
returns boolean language plpgsql security definer set search_path=public as $$
declare s public.trade_sessions%rowtype;
begin
  select * into s from public.trade_sessions where id=p_session_id and status='open' for update;
  if not found or (s.user_a<>auth.uid() and s.user_b<>auth.uid()) then raise exception 'Trade not available'; end if;
  if s.user_a=auth.uid() then
    update public.trade_sessions set accepted_a=p_accept,confirmed_a=false,confirmed_b=false,updated_at=now() where id=p_session_id;
  else
    update public.trade_sessions set accepted_b=p_accept,confirmed_a=false,confirmed_b=false,updated_at=now() where id=p_session_id;
  end if;
  return true;
end;
$$;

create or replace function public.trade_set_confirmed(p_session_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
declare s public.trade_sessions%rowtype;
begin
  select * into s from public.trade_sessions where id=p_session_id and status='open' for update;
  if not found or (s.user_a<>auth.uid() and s.user_b<>auth.uid()) then raise exception 'Trade not available'; end if;
  if not (s.accepted_a and s.accepted_b) then raise exception 'Both players must accept first'; end if;
  if s.user_a=auth.uid() then
    update public.trade_sessions set confirmed_a=true,
      status=case when confirmed_b then 'countdown' else 'open' end,
      countdown_started_at=case when confirmed_b then coalesce(countdown_started_at,now()) else null end,updated_at=now()
    where id=p_session_id;
  else
    update public.trade_sessions set confirmed_b=true,
      status=case when confirmed_a then 'countdown' else 'open' end,
      countdown_started_at=case when confirmed_a then coalesce(countdown_started_at,now()) else null end,updated_at=now()
    where id=p_session_id;
  end if;
  return true;
end;
$$;

create or replace function public.trade_cancel(p_session_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  update public.trade_sessions set status='cancelled',updated_at=now()
  where id=p_session_id and (user_a=auth.uid() or user_b=auth.uid()) and status in ('open','countdown');
  return found;
end;
$$;

create or replace function public.trade_send_message(p_session_id uuid,p_message text)
returns bigint language plpgsql security definer set search_path=public as $$
declare mid bigint;
begin
  if char_length(trim(coalesce(p_message,'')))<1 or char_length(p_message)>500 then raise exception 'Invalid message'; end if;
  if not exists(select 1 from public.trade_sessions where id=p_session_id and
    (user_a=auth.uid() or user_b=auth.uid()) and status in ('open','countdown')) then
    raise exception 'Trade not available';
  end if;
  insert into public.trade_messages(session_id,sender_id,message)
  values(p_session_id,auth.uid(),trim(p_message)) returning id into mid;
  return mid;
end;
$$;

create or replace function public.trade_finalize(p_session_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
declare s public.trade_sessions%rowtype; it record;
begin
  select * into s from public.trade_sessions where id=p_session_id for update;
  if not found or (s.user_a<>auth.uid() and s.user_b<>auth.uid()) then raise exception 'Trade not found'; end if;
  if s.status='completed' then return true; end if;
  if s.status<>'countdown' or s.countdown_started_at is null or now()<s.countdown_started_at+interval '5 seconds' then
    raise exception 'Countdown not finished';
  end if;

  perform 1 from public.profiles where id=s.user_a and coins>=s.offer_a_coins for update;
  if not found then raise exception 'Player A no longer has enough coins'; end if;
  perform 1 from public.profiles where id=s.user_b and coins>=s.offer_b_coins for update;
  if not found then raise exception 'Player B no longer has enough coins'; end if;

  update public.profiles set coins=coins-s.offer_a_coins+s.offer_b_coins,updated_at=now() where id=s.user_a;
  update public.profiles set coins=coins-s.offer_b_coins+s.offer_a_coins,updated_at=now() where id=s.user_b;

  for it in select * from public.trade_items where session_id=s.id order by id loop
    update public.inventory set quantity=quantity-it.quantity
    where user_id=it.owner_id and item_type=it.item_type and item_id=it.item_id and quantity>=it.quantity;
    if not found then raise exception 'Inventory changed during trade'; end if;

    insert into public.inventory(user_id,item_type,item_id,quantity)
    values(case when it.owner_id=s.user_a then s.user_b else s.user_a end,it.item_type,it.item_id,it.quantity)
    on conflict(user_id,item_type,item_id)
    do update set quantity=public.inventory.quantity+excluded.quantity;
  end loop;

  delete from public.inventory where quantity<=0;
  update public.trade_sessions set status='completed',updated_at=now() where id=s.id;
  update public.trade_requests set status='completed',updated_at=now() where id=s.request_id;
  return true;
end;
$$;

grant execute on function public.trade_create_request(uuid) to authenticated;
grant execute on function public.trade_respond_request(uuid,boolean) to authenticated;
grant execute on function public.trade_cancel_request(uuid) to authenticated;
grant execute on function public.trade_set_offer(uuid,bigint,jsonb) to authenticated;
grant execute on function public.trade_set_accepted(uuid,boolean) to authenticated;
grant execute on function public.trade_set_confirmed(uuid) to authenticated;
grant execute on function public.trade_cancel(uuid) to authenticated;
grant execute on function public.trade_send_message(uuid,text) to authenticated;
grant execute on function public.trade_finalize(uuid) to authenticated;
