-- ============================================================
-- ILLEGAL RUNNER — ÉCHANGES ENTRE AMIS
-- ============================================================

alter table public.inventory drop constraint if exists inventory_item_type_check;
alter table public.inventory add column if not exists quantity integer not null default 1;
alter table public.inventory add constraint inventory_item_type_check
  check (item_type in ('background','character','obstacle','coin'));
update public.inventory set quantity=1 where quantity is null or quantity < 1;

create table if not exists public.trade_requests (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check(status in ('pending','accepted','declined','cancelled','completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check(sender_id <> receiver_id)
);

create table if not exists public.trade_sessions (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null unique references public.trade_requests(id) on delete cascade,
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'open' check(status in ('open','countdown','completed','cancelled')),
  offer_a_coins bigint not null default 0 check(offer_a_coins >= 0),
  offer_b_coins bigint not null default 0 check(offer_b_coins >= 0),
  accepted_a boolean not null default false,
  accepted_b boolean not null default false,
  confirmed_a boolean not null default false,
  confirmed_b boolean not null default false,
  countdown_started_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check(user_a <> user_b)
);

create table if not exists public.trade_items (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.trade_sessions(id) on delete cascade,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  item_type text not null check(item_type in ('background','character','obstacle','coin')),
  item_id text not null,
  quantity integer not null check(quantity > 0),
  unique(session_id,owner_id,item_type,item_id)
);

create table if not exists public.trade_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.trade_sessions(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  message text not null check(char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.trade_requests enable row level security;
alter table public.trade_sessions enable row level security;
alter table public.trade_items enable row level security;
alter table public.trade_messages enable row level security;

drop policy if exists trade_requests_select on public.trade_requests;
drop policy if exists trade_sessions_select on public.trade_sessions;
drop policy if exists trade_items_select on public.trade_items;
drop policy if exists trade_messages_select on public.trade_messages;

create policy trade_requests_select on public.trade_requests
for select using (auth.uid()=sender_id or auth.uid()=receiver_id);

create policy trade_sessions_select on public.trade_sessions
for select using (auth.uid()=user_a or auth.uid()=user_b);

create policy trade_items_select on public.trade_items
for select using (
  exists(select 1 from public.trade_sessions s
    where s.id=trade_items.session_id and (s.user_a=auth.uid() or s.user_b=auth.uid()))
);

create policy trade_messages_select on public.trade_messages
for select using (
  exists(select 1 from public.trade_sessions s
    where s.id=trade_messages.session_id and (s.user_a=auth.uid() or s.user_b=auth.uid()))
);



create or replace function public.trade_poll_requests()
returns table(
  id uuid,
  sender_id uuid,
  receiver_id uuid,
  status text,
  created_at timestamptz,
  sender_username text,
  receiver_username text,
  session_id uuid
)
language sql
security definer
set search_path=public,auth
set row_security=off
as $$
  select
    r.id,
    r.sender_id,
    r.receiver_id,
    r.status,
    r.created_at,
    coalesce(
      nullif(btrim(ps.username),''),
      nullif(btrim(us.raw_user_meta_data->>'username'),''),
      split_part(coalesce(us.email,''),'@',1),
      'Joueur'
    ) as sender_username,
    coalesce(
      nullif(btrim(pr.username),''),
      nullif(btrim(ur.raw_user_meta_data->>'username'),''),
      split_part(coalesce(ur.email,''),'@',1),
      'Joueur'
    ) as receiver_username,
    s.id as session_id
  from public.trade_requests r
  left join public.trade_sessions s on s.request_id=r.id
  left join public.profiles ps on ps.id=r.sender_id
  left join public.profiles pr on pr.id=r.receiver_id
  left join auth.users us on us.id=r.sender_id
  left join auth.users ur on ur.id=r.receiver_id
  where r.sender_id=auth.uid() or r.receiver_id=auth.uid()
  order by r.created_at desc
  limit 50;
$$;

revoke all on function public.trade_poll_requests() from public,anon;
grant execute on function public.trade_poll_requests() to authenticated;

create index if not exists trade_requests_participants_idx on public.trade_requests(sender_id,receiver_id,status);
create index if not exists trade_sessions_participants_idx on public.trade_sessions(user_a,user_b,status);
create index if not exists trade_items_session_idx on public.trade_items(session_id,owner_id);
create index if not exists trade_messages_session_idx on public.trade_messages(session_id,created_at);

create or replace function public.trade_create_request(p_friend_id uuid)
returns uuid language plpgsql security definer set search_path=public as $$
declare rid uuid;
begin
  if p_friend_id is null or p_friend_id=auth.uid() then raise exception 'Invalid friend'; end if;
  if not exists (
    select 1 from public.friends f
    where f.status='accepted' and
      ((f.user_id=auth.uid() and f.friend_id=p_friend_id)
       or (f.user_id=p_friend_id and f.friend_id=auth.uid()))
  ) then raise exception 'You are not friends'; end if;
  select id into rid from public.trade_requests
  where status='pending' and
    ((sender_id=auth.uid() and receiver_id=p_friend_id)
     or (sender_id=p_friend_id and receiver_id=auth.uid()))
  order by created_at desc limit 1;
  if rid is not null then return rid; end if;
  insert into public.trade_requests(sender_id,receiver_id) values(auth.uid(),p_friend_id) returning id into rid;
  return rid;
end;
$$;

create or replace function public.trade_respond_request(p_request_id uuid,p_accept boolean)
returns uuid language plpgsql security definer set search_path=public as $$
declare req public.trade_requests%rowtype; sid uuid;
begin
  select * into req from public.trade_requests
  where id=p_request_id and receiver_id=auth.uid() and status='pending' for update;
  if not found then raise exception 'Trade request not found'; end if;
  if not p_accept then
    update public.trade_requests set status='declined',updated_at=now() where id=req.id;
    return null;
  end if;
  insert into public.trade_sessions(request_id,user_a,user_b) values(req.id,req.sender_id,req.receiver_id) returning id into sid;
  update public.trade_requests set status='accepted',updated_at=now() where id=req.id;
  return sid;
end;
$$;

create or replace function public.trade_cancel_request(p_request_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  update public.trade_requests set status='cancelled',updated_at=now()
  where id=p_request_id and sender_id=auth.uid() and status='pending';
  return found;
end;
$$;

create or replace function public.trade_set_offer(p_session_id uuid,p_coins bigint,p_items jsonb)
returns boolean language plpgsql security definer set search_path=public as $$
declare s public.trade_sessions%rowtype; x jsonb; t text; iid text; qty integer; owned integer;
begin
  if p_coins is null or p_coins < 0 then raise exception 'Invalid coins'; end if;
  select * into s from public.trade_sessions where id=p_session_id and status='open' for update;
  if not found or (s.user_a<>auth.uid() and s.user_b<>auth.uid()) then raise exception 'Trade not available'; end if;
  if (select coins from public.profiles where id=auth.uid()) < p_coins then raise exception 'Not enough coins'; end if;
  if jsonb_typeof(coalesce(p_items,'[]'::jsonb)) <> 'array' then raise exception 'Invalid items'; end if;

  delete from public.trade_items where session_id=p_session_id and owner_id=auth.uid();
  for x in select * from jsonb_array_elements(coalesce(p_items,'[]'::jsonb)) loop
    t:=x->>'item_type'; iid:=x->>'item_id'; qty:=greatest(0,(x->>'quantity')::integer);
    if qty>0 then
      if t not in ('background','character','obstacle','coin') then raise exception 'Invalid item type'; end if;
      select quantity into owned from public.inventory
      where user_id=auth.uid() and item_type=t and item_id=iid;
      if coalesce(owned,0)<qty then raise exception 'Item quantity not owned'; end if;
      insert into public.trade_items(session_id,owner_id,item_type,item_id,quantity)
      values(p_session_id,auth.uid(),t,iid,qty);
    end if;
  end loop;

  if s.user_a=auth.uid() then
    update public.trade_sessions set offer_a_coins=p_coins,accepted_a=false,accepted_b=false,
      confirmed_a=false,confirmed_b=false,status='open',countdown_started_at=null,updated_at=now()
    where id=p_session_id;
  else
    update public.trade_sessions set offer_b_coins=p_coins,accepted_a=false,accepted_b=false,
      confirmed_a=false,confirmed_b=false,status='open',countdown_started_at=null,updated_at=now()
    where id=p_session_id;
  end if;
  return true;
end;
$$;

create or replace function public.trade_set_accepted(p_session_id uuid,p_accept boolean)
returns boolean language plpgsql security definer set search_path=public as $$
declare s public.trade_sessions%rowtype;
begin
  select * into s from public.trade_sessions where id=p_session_id and status='open' for update;
  if not found or (s.user_a<>auth.uid() and s.user_b<>auth.uid()) then raise exception 'Trade not available'; end if;
  if s.user_a=auth.uid() then
    update public.trade_sessions set accepted_a=p_accept,confirmed_a=false,confirmed_b=false,updated_at=now() where id=p_session_id;
  else
    update public.trade_sessions set accepted_b=p_accept,confirmed_a=false,confirmed_b=false,updated_at=now() where id=p_session_id;
  end if;
  return true;
end;
$$;

create or replace function public.trade_set_confirmed(p_session_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
declare s public.trade_sessions%rowtype;
begin
  select * into s from public.trade_sessions where id=p_session_id and status='open' for update;
  if not found or (s.user_a<>auth.uid() and s.user_b<>auth.uid()) then raise exception 'Trade not available'; end if;
  if not (s.accepted_a and s.accepted_b) then raise exception 'Both players must accept first'; end if;
  if s.user_a=auth.uid() then
    update public.trade_sessions set confirmed_a=true,
      status=case when confirmed_b then 'countdown' else 'open' end,
      countdown_started_at=case when confirmed_b then coalesce(countdown_started_at,now()) else null end,updated_at=now()
    where id=p_session_id;
  else
    update public.trade_sessions set confirmed_b=true,
      status=case when confirmed_a then 'countdown' else 'open' end,
      countdown_started_at=case when confirmed_a then coalesce(countdown_started_at,now()) else null end,updated_at=now()
    where id=p_session_id;
  end if;
  return true;
end;
$$;

create or replace function public.trade_cancel(p_session_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  update public.trade_sessions set status='cancelled',updated_at=now()
  where id=p_session_id and (user_a=auth.uid() or user_b=auth.uid()) and status in ('open','countdown');
  return found;
end;
$$;

create or replace function public.trade_send_message(p_session_id uuid,p_message text)
returns bigint language plpgsql security definer set search_path=public as $$
declare mid bigint;
begin
  if char_length(trim(coalesce(p_message,'')))<1 or char_length(p_message)>500 then raise exception 'Invalid message'; end if;
  if not exists(select 1 from public.trade_sessions where id=p_session_id and
    (user_a=auth.uid() or user_b=auth.uid()) and status in ('open','countdown')) then
    raise exception 'Trade not available';
  end if;
  insert into public.trade_messages(session_id,sender_id,message)
  values(p_session_id,auth.uid(),trim(p_message)) returning id into mid;
  return mid;
end;
$$;

create or replace function public.trade_finalize(p_session_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
declare s public.trade_sessions%rowtype; it record;
begin
  select * into s from public.trade_sessions where id=p_session_id for update;
  if not found or (s.user_a<>auth.uid() and s.user_b<>auth.uid()) then raise exception 'Trade not found'; end if;
  if s.status='completed' then return true; end if;
  if s.status<>'countdown' or s.countdown_started_at is null or now()<s.countdown_started_at+interval '5 seconds' then
    raise exception 'Countdown not finished';
  end if;

  perform 1 from public.profiles where id=s.user_a and coins>=s.offer_a_coins for update;
  if not found then raise exception 'Player A no longer has enough coins'; end if;
  perform 1 from public.profiles where id=s.user_b and coins>=s.offer_b_coins for update;
  if not found then raise exception 'Player B no longer has enough coins'; end if;

  update public.profiles set coins=coins-s.offer_a_coins+s.offer_b_coins,updated_at=now() where id=s.user_a;
  update public.profiles set coins=coins-s.offer_b_coins+s.offer_a_coins,updated_at=now() where id=s.user_b;

  for it in select * from public.trade_items where session_id=s.id order by id loop
    update public.inventory set quantity=quantity-it.quantity
    where user_id=it.owner_id and item_type=it.item_type and item_id=it.item_id and quantity>=it.quantity;
    if not found then raise exception 'Inventory changed during trade'; end if;

    insert into public.inventory(user_id,item_type,item_id,quantity)
    values(case when it.owner_id=s.user_a then s.user_b else s.user_a end,it.item_type,it.item_id,it.quantity)
    on conflict(user_id,item_type,item_id)
    do update set quantity=public.inventory.quantity+excluded.quantity;
  end loop;

  delete from public.inventory where quantity<=0;
  update public.trade_sessions set status='completed',updated_at=now() where id=s.id;
  update public.trade_requests set status='completed',updated_at=now() where id=s.request_id;
  return true;
end;
$$;

grant execute on function public.trade_create_request(uuid) to authenticated;
grant execute on function public.trade_respond_request(uuid,boolean) to authenticated;
grant execute on function public.trade_cancel_request(uuid) to authenticated;
grant execute on function public.trade_set_offer(uuid,bigint,jsonb) to authenticated;
grant execute on function public.trade_set_accepted(uuid,boolean) to authenticated;
grant execute on function public.trade_set_confirmed(uuid) to authenticated;
grant execute on function public.trade_cancel(uuid) to authenticated;
grant execute on function public.trade_send_message(uuid,text) to authenticated;
grant execute on function public.trade_finalize(uuid) to authenticated;
