(() => {
'use strict'
const cfg=window.IR_CONFIG||{}
const sb=window.supabase&&cfg.SUPABASE_URL?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null
const S={user:null,requestId:null,sessionId:null,names:{},sig:'',timer:null,lastChat:''}
const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))
const map={world:'background',character:'character',coin:'coin'},rev={background:'world',character:'character',coin:'coin'}
const key=(u,t)=>'irRarityCollection_'+u+'_'+t
const read=(u,t)=>{try{const x=JSON.parse(localStorage.getItem(key(u,t))||'{}');return x&&typeof x==='object'?x:{}}catch{return {}}}
const write=(u,t,x)=>{try{localStorage.setItem(key(u,t),JSON.stringify(x))}catch{}}
const catalog=(t,id)=>{const a=window.IR_PACK_CATALOG?.[t]||[],x=a.find(v=>v[0]===id);return x?{emoji:x[1],name:x[2]}:{emoji:'📦',name:String(id).toUpperCase()}}
const layer=document.createElement('div');layer.id='irTradeLayer';document.body.appendChild(layer)
const css=document.createElement('style');css.textContent='#irTradeLayer{position:fixed;inset:0;z-index:2147483600;display:none;align-items:center;justify-content:center;padding:12px;background:rgba(1,4,10,.8);backdrop-filter:blur(7px)}#irTradeLayer .tm{width:min(1080px,96vw);max-height:94vh;overflow:auto;background:#070c16;color:#fff;border:1px solid rgba(0,229,255,.35);border-radius:18px;box-shadow:0 0 55px rgba(0,229,255,.18)}#irTradeLayer .th{display:flex;justify-content:space-between;align-items:center;padding:14px 18px;border-bottom:1px solid #1b2940}#irTradeLayer .tb{padding:15px}#irTradeLayer .grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}#irTradeLayer .card{padding:12px;border:1px solid #1b2940;border-radius:12px;background:#0a101b}#irTradeLayer .items{max-height:260px;overflow:auto}#irTradeLayer .item{display:flex;align-items:center;gap:8px;margin:5px 0;padding:6px;border-radius:8px;background:#0d1624}.grow{flex:1;min-width:0}.sub{color:#91a0b7;font-size:12px}#irTradeLayer button,#irTradeLayer input,#irTradeLayer textarea{font:inherit}#irTradeLayer button{border:1px solid #274765;background:#0d1929;color:#fff;border-radius:8px;padding:8px 11px;font-weight:900;cursor:pointer}#irTradeLayer .primary{background:linear-gradient(90deg,#00a7cf,#d72583);border:0}#irTradeLayer .danger{color:#ff8da5;border-color:#633244}#irTradeLayer input,#irTradeLayer textarea{box-sizing:border-box;background:#050a12;color:#fff;border:1px solid #25344e;border-radius:8px;padding:8px}#irTradeLayer input{width:100%}#irTradeLayer .actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}#irTradeLayer .chat{border-top:1px solid #1b2940;margin-top:12px;padding-top:12px}#irTradeLayer .log{height:140px;overflow:auto;background:#040810;border-radius:8px;padding:8px}#irTradeLayer .msg{font-size:13px;margin-bottom:6px}#irTradeLayer .count{font-size:36px;font-weight:900;text-align:center;color:#ffd45c;padding:12px}@media(max-width:760px){#irTradeLayer .grid{grid-template-columns:1fr}}';document.head.appendChild(css)
function close(){layer.style.display='none';S.requestId=null;S.sessionId=null;S.sig='';if(S.timer){clearInterval(S.timer);S.timer=null}}
function show(x){layer.innerHTML=x;layer.style.display='flex'}
async function rpc(n,a){const r=await sb.rpc(n,a);if(r.error)throw r.error;return r.data}
async function refreshUser(){if(!sb)return;const q=await sb.auth.getSession();const u=q.data?.session?.user||null;if(u?.id!==S.user?.id){S.user=u;if(u){for(const t of ['world','character','coin']){const d=read(u.id,t),rows=Object.entries(d).filter(([,v])=>Number(v)>0).map(([id,v])=>({user_id:u.id,item_type:map[t],item_id:id,quantity:Number(v)}));if(rows.length)await sb.from('inventory').upsert(rows,{onConflict:'user_id,item_type,item_id'})}}}}
window.addEventListener('ir:collectionChanged',e=>{const d=e.detail;if(!S.user||d?.uid!==S.user.id||!map[d.type])return;const rows=Object.entries(d.data||{}).filter(([,v])=>Number(v)>0).map(([id,v])=>({user_id:S.user.id,item_type:map[d.type],item_id:id,quantity:Number(v)}));if(rows.length)sb.from('inventory').upsert(rows,{onConflict:'user_id,item_type,item_id'});for(const [id,v] of Object.entries(d.data||{}))if(Number(v)<=0)sb.from('inventory').delete().eq('user_id',S.user.id).eq('item_type',map[d.type]).eq('item_id',id)})
function decorateFriends(){document.querySelectorAll('#friendList .friend[data-trade-friend-id]').forEach(el=>{const id=el.dataset.tradeFriendId;const sp=el.querySelector('span');const nm=(sp?.innerText||'').split('\n')[0].replace(/^👤\s*/,'').trim();if(nm)S.names[id]=nm;if(!el.querySelector('[data-trade-open]')){const b=document.createElement('button');b.type='button';b.dataset.tradeOpen=id;b.textContent='🔄 ÉCHANGE';el.appendChild(b)}})}
function owned(){const a=[];if(!S.user)return a;for(const t of ['world','character','coin'])for(const [id,v] of Object.entries(read(S.user.id,t))){const q=Math.floor(Number(v)||0);if(q>0){const m=catalog(t,id);a.push({type:t,id,quantity:q,emoji:m.emoji,name:m.name})}}return a}
function requestView(r){const incoming=r.receiver_id===S.user.id;S.requestId=r.id;const who=esc(S.names[incoming?r.sender_id:r.receiver_id]||'ton ami');if(incoming){show('<div class="tm"><div class="th"><h2>🔄 Demande d’échange</h2><button id="tx">✕</button></div><div class="tb"><h3>👤 '+who+' veut échanger avec toi.</h3><p class="sub">Accepte pour ouvrir le GUI d’échange.</p><div class="actions"><button class="primary" id="ta">✅ ACCEPTER</button><button class="danger" id="tr">❌ REFUSER</button></div></div></div>');document.getElementById('ta').onclick=()=>respond(true);document.getElementById('tr').onclick=()=>respond(false)}else{show('<div class="tm"><div class="th"><h2>🔄 Échange avec '+who+'</h2><button id="tx">✕</button></div><div class="tb"><div class="card" style="margin-bottom:10px"><h3>⏳ La demande d’échange est en attente.</h3><p class="sub">Le GUI est ouvert pour toi, mais les boutons restent verrouillés jusqu’à l’acceptation de ton ami.</p></div><div class="grid"><div class="card"><h3>👤 Moi</h3><div class="sub">🪙 Argent et objets disponibles après acceptation.</div><div class="actions"><button disabled>💾 METTRE À JOUR</button><button disabled>✅ ACCEPTER</button></div></div><div class="card"><h3>👤 '+who+'</h3><div class="sub">⏳ En attente d’acceptation.</div></div></div><div class="actions"><button class="danger" id="tcancel">ANNULER L’ÉCHANGE</button></div></div></div>');document.getElementById('tcancel').onclick=async()=>{try{await rpc('trade_cancel_request',{p_request_id:S.requestId})}catch{}close()}}document.getElementById('tx').onclick=close}
async function respond(ok){try{const sid=await rpc('trade_respond_request',{p_request_id:S.requestId,p_accept:ok});if(!ok){close();return}S.sessionId=sid;await render()}catch(e){alert('❌ '+(e.message||'Erreur'))}}
function editor(){return '<label class="sub">🪙 Argent offert</label><input id="cash" type="number" min="0" value="'+(S.cash||0)+'"><div class="items">'+owned().map(x=>'<div class="item"><span>'+x.emoji+'</span><span class="grow">'+esc(x.name)+' <span class="sub">(x'+x.quantity+')</span></span><input data-q data-t="'+map[x.type]+'" data-i="'+esc(x.id)+'" data-max="'+x.quantity+'" type="number" min="0" max="'+x.quantity+'" value="'+(x.offered||0)+'" style="width:65px"></div>').join('')+'</div>'}
function readOffer(){const items=[];document.querySelectorAll('#irTradeLayer [data-q]').forEach(x=>{const q=Math.max(0,Math.min(Number(x.dataset.max)||0,Math.floor(Number(x.value)||0)));if(q)items.push({item_type:x.dataset.t,item_id:x.dataset.i,quantity:q})});return{coins:Math.max(0,Math.floor(Number(document.getElementById('cash')?.value)||0)),items}}
async function saveOffer(){try{const o=readOffer();await rpc('trade_set_offer',{p_session_id:S.sessionId,p_coins:o.coins,p_items:o.items});S.cash=o.coins;S.sig='';await render()}catch(e){alert('❌ '+(e.message||'Offre invalide'))}}
async function actAccept(v){try{await rpc('trade_set_accepted',{p_session_id:S.sessionId,p_accept:v});S.sig='';await render()}catch(e){alert('❌ '+(e.message||'Erreur'))}}
async function confirm(){try{await rpc('trade_set_confirmed',{p_session_id:S.sessionId});S.sig='';await render()}catch(e){alert('❌ '+(e.message||'Erreur'))}}
async function cancel(){try{if(S.sessionId)await rpc('trade_cancel',{p_session_id:S.sessionId})}catch{}close()}
async function sendChat(){const x=document.getElementById('chatInput'),m=String(x?.value||'').trim();if(!m)return;try{await rpc('trade_send_message',{p_session_id:S.sessionId,p_message:m});x.value='';loadChat()}catch(e){alert('❌ '+(e.message||'Chat indisponible'))}}
async function loadChat(){if(!S.sessionId)return;const q=await sb.from('trade_messages').select('sender_id,message').eq('session_id',S.sessionId).order('created_at',{ascending:true}).limit(100);const l=document.getElementById('chatLog');if(q.error||!l)return;const h=(q.data||[]).map(m=>'<div class="msg"><b>'+(m.sender_id===S.user.id?'Moi':'Ami')+':</b> '+esc(m.message)+'</div>').join('')||'<div class="sub">Aucun message.</div>';if(h!==S.lastChat){l.innerHTML=h;l.scrollTop=l.scrollHeight;S.lastChat=h}}
async function render(){if(!S.sessionId)return;const q=await sb.from('trade_sessions').select('*').eq('id',S.sessionId).maybeSingle();if(q.error||!q.data){close();return}const s=q.data;if(s.status==='cancelled'){alert('❌ L’échange a été annulé.');close();return}if(s.status==='completed'){const inv=await sb.from('inventory').select('item_type,item_id,quantity').eq('user_id',S.user.id);if(!inv.error){const g={world:{},character:{},coin:{}};(inv.data||[]).forEach(x=>{const t=rev[x.item_type];if(t&&Number(x.quantity)>0)g[t][x.item_id]=Number(x.quantity)});Object.keys(g).forEach(t=>write(S.user.id,t,g[t]))}alert('✅ Échange confirmé !');close();return}
const meA=s.user_a===S.user.id,other=meA?s.user_b:s.user_a,myOk=meA?s.accepted_a:s.accepted_b,otherOk=meA?s.accepted_b:s.accepted_a,myConf=meA?s.confirmed_a:s.confirmed_b,nm=esc(S.names[other]||'ton ami'),sig=JSON.stringify([s.status,s.offer_a_coins,s.offer_b_coins,s.accepted_a,s.accepted_b,s.confirmed_a,s.confirmed_b]);const it=await sb.from('trade_items').select('owner_id,item_type,item_id,quantity').eq('session_id',S.sessionId).order('id');const items=it.data||[];if(sig===S.sig&&s.status!=='countdown'){loadChat();return}S.sig=sig;S.cash=meA?s.offer_a_coins:s.offer_b_coins;const their=items.filter(x=>x.owner_id===other);let countdown='';if(s.status==='countdown'){const start=new Date(s.countdown_started_at).getTime();if(S.timer)clearInterval(S.timer);S.timer=setInterval(()=>{const b=document.getElementById('cd');const left=Math.max(0,5-(Date.now()-start)/1000);if(b)b.textContent=left.toFixed(1)+' s';if(left<=0){clearInterval(S.timer);S.timer=null;rpc('trade_finalize',{p_session_id:S.sessionId}).catch(()=>{});render()}},100);countdown='<div class="count">⏳ <span id="cd">5.0</span></div>'}
const otherCash=meA?s.offer_b_coins:s.offer_a_coins;const canConfirm=myOk&&otherOk&&!myConf;show('<div class="tm"><div class="th"><h2>🔄 Échange avec '+nm+'</h2><button id="xc">✕</button></div><div class="tb"><p class="sub">'+(s.status==='countdown'?'Les deux ont confirmé. Annulation possible pendant le compte à rebours.':myOk&&otherOk?'Les deux ont accepté : confirme pour lancer le transfert.':'Tu peux modifier ton offre puis accepter.')+'</p>'+countdown+'<div class="grid"><div class="card"><h3>👤 Moi</h3>'+editor()+'<div class="actions"><button class="primary" id="save">💾 METTRE À JOUR</button><button id="acc">'+(myOk?'↩️ ANNULER ACCEPTATION':'✅ ACCEPTER')+'</button>'+(canConfirm?'<button class="primary" id="conf">🔒 CONFIRMER</button>':'')+'</div></div><div class="card"><h3>👤 '+nm+'</h3><p>🪙 '+Number(otherCash||0).toLocaleString('fr-FR')+' pièces</p><div class="items">'+(their.length?their.map(x=>{const m=catalog(rev[x.item_type]||x.item_type,x.item_id);return '<div class="item"><span>'+m.emoji+'</span><span class="grow">'+esc(m.name)+'</span><b>x'+x.quantity+'</b></div>'}).join(''):'<div class="sub">Aucun objet offert.</div>')+'</div><p class="sub">'+(otherOk?'✅ A accepté':'⏳ N’a pas encore accepté')+'</p></div></div><div class="chat"><h3>💬 Chat</h3><div id="chatLog" class="log"></div><div class="actions"><input id="chatInput" maxlength="500" placeholder="Écrire un message…"><button id="send">ENVOYER</button></div></div><div class="actions"><button class="danger" id="cancel">❌ ANNULER L’ÉCHANGE</button></div></div></div>');document.getElementById('xc').onclick=cancel;document.getElementById('cancel').onclick=cancel;document.getElementById('save').onclick=saveOffer;document.getElementById('acc').onclick=()=>actAccept(!myOk);document.getElementById('send').onclick=sendChat;document.getElementById('chatInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendChat()}};const cf=document.getElementById('conf');if(cf)cf.onclick=confirm;loadChat()}
async function poll(){if(!S.user)return;const q=await sb.from('trade_requests').select('id,sender_id,receiver_id,status').or('sender_id.eq.'+S.user.id+',receiver_id.eq.'+S.user.id).order('created_at',{ascending:false}).limit(20);if(q.error)return;const p=q.data?.find(x=>x.status==='pending');if(p&&!layer.matches(':visible'))requestView(p);if(S.requestId&&!S.sessionId){const a=q.data?.find(x=>x.id===S.requestId&&x.status==='accepted');if(a){const z=await sb.from('trade_sessions').select('id').eq('request_id',S.requestId).maybeSingle();if(z.data?.id){S.sessionId=z.data.id;S.sig='';render()}}const d=q.data?.find(x=>x.id===S.requestId&&['declined','cancelled'].includes(x.status));if(d){alert(d.status==='declined'?'❌ La demande d’échange a été refusée.':'❌ La demande a été annulée.');close()}}if(S.sessionId){await render();loadChat()}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-trade-open]');if(!b)return;e.preventDefault();e.stopPropagation();(async()=>{try{const id=await rpc('trade_create_request',{p_friend_id:b.dataset.tradeOpen});S.requestId=id;const q=await sb.from('trade_requests').select('id,sender_id,receiver_id,status').eq('id',id).maybeSingle();if(q.data)requestView(q.data)}catch(x){alert('❌ '+(x.message||'Demande impossible'))}})()},true)
const ob=new MutationObserver(decorateFriends);function decorateFriends(){document.querySelectorAll('#friendList .friend[data-trade-friend-id]').forEach(el=>{const id=el.dataset.tradeFriendId;if(!id)return;const sp=el.querySelector('span');const nm=(sp?.innerText||'').split('\n')[0].replace(/^👤\s*/,'').trim();if(nm)S.names[id]=nm;if(!el.querySelector('[data-trade-open]')){const b=document.createElement('button');b.type='button';b.dataset.tradeOpen=id;b.textContent='🔄 ÉCHANGE';el.appendChild(b)}})}
async function init(){const box=document.getElementById('friendList');if(box)ob.observe(box,{childList:true,subtree:true});decorateFriends();await refreshUser();setInterval(async()=>{await refreshUser();decorateFriends();await poll()},900)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init()
})()